LeaveManagementT5/Controllers/ApplicationRolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace LeaveManagementT5.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class ApplicationRolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public ApplicationRolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        //List all the roles created by users
        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model)
        {
            
            if (!await _roleManager.RoleExistsAsync(model.Name))
            {
                
                var newRole = new IdentityRole
                {
                    Name = model.Name
                };
                var result = await _roleManager.CreateAsync(newRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    
                    ModelState.AddModelError(string.Empty, "The Role Could Not Be Created.");
                }
            }
           

            return View(model);
        }


    }
}

LeaveManagementT5/Controllers/LeaveRequestController.cs
using LeaveManagementT5.Data;
using LeaveManagementT5.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LeaveManagementT5.Services;

[Authorize]
public class LeaveRequestController : Controller
{
    private readonly UserManager<IdentityUser> _userManager;
    private readonly AppDbContext _context;
    private readonly IEmailSender _emailSender;

    public LeaveRequestController(UserManager<IdentityUser> userManager, AppDbContext context, IEmailSender emailSender)
    {
        _userManager = userManager;
        _context = context;
        _emailSender = emailSender;
    }

    [Authorize(Roles = "Admin")]
    public IActionResult Index(string status)
    {


        var query = _context.LeaveRequest
            .Include(lr => lr.Employee)
            .Include(lr => lr.LeaveType)
            .AsQueryable(); // Create a base query to build upon

        // Check if a status filter is provided
        if (!string.IsNullOrEmpty(status))
        {
            query = query.Where(lr => lr.Status == status);
        }

        var leaveRequests = query.ToList();

        if (TempData.ContainsKey("InsufficientLeaveDaysMessage"))
        {
            ViewBag.InsufficientLeaveDaysMessage = TempData["InsufficientLeaveDaysMessage"].ToString();
        }

        return View(leaveRequests);
    }

    [Authorize(Roles = "Employee")]
    public IActionResult Create()
    {
        // Load leave types into a dropdown for selection
        var leaveTypes = _context.LeaveTypes.ToList();
        ViewBag.LeaveTypes = new SelectList(leaveTypes, "Id", "Name", "DefaultDays");
        return View();
    }

    [HttpPost]
    [Authorize(Roles = "Employee")]
    public IActionResult Create(LeaveRequest leaveRequest)
    {
        
        leaveRequest.Status = "Pending";

        var user = _userManager.GetUserAsync(User).Result;
        leaveRequest.EmployeeId = user.Id;

        
        int requestedDays = (leaveRequest.EndDate - leaveRequest.StartDate).Days;

        var selectedLeaveType = _context.LeaveTypes.FirstOrDefault(lt => lt.Id == leaveRequest.LeaveTypeId);

        if (selectedLeaveType != null && requestedDays <= selectedLeaveType.DefaultDays)
        {
            
            _context.LeaveRequest.Add(leaveRequest);
            _context.SaveChanges();
            return RedirectToAction("MyLeaveRequests");
        }
        else
        {
           
            ViewBag.AlertClass = "alert-danger";
            ViewBag.AlertMessage = "Requested days exceed the allowed limit for this leave type.";
            
            ModelState.AddModelError("EndDate", "Requested days exceed the allowed limit for this leave type.");
        }

        
        Console.WriteLine("Den gubben gick inte");
        var leaveTypes = _context.LeaveTypes.ToList();
        ViewBag.LeaveTypes = new SelectList(leaveTypes, "Id", "Name");
        return View(leaveRequest);
    }

    [Authorize(Roles = "Admin")]
    public IActionResult Edit(int id)
    {
        var leaveRequest = _context.LeaveRequest.FirstOrDefault(lr => lr.Id == id);
        if (leaveRequest == null)
        {
            return NotFound();
        }

        // Load status options (accepted and declined) as SelectList
        var statusOptions = new List<SelectListItem>
    {
        new SelectListItem { Value = "Pending", Text = "Pending" },
        new SelectListItem { Value = "Accepted", Text = "Accepted" },
        new SelectListItem { Value = "Declined", Text = "Declined" }
    };
        ViewBag.StatusOptions = new SelectList(statusOptions, "Value", "Text");

        return View(leaveRequest);
    }



    //Den här fungerar dåligt, någon konflikt LeaveRequest tabellen och LeaveType, Exception blir Castat
    //Använd dig av AccepRequest och DenyRequest för att hantera en användares LeaveRequest 
    [HttpPost]
    [Authorize(Roles = "Admin")]
    public IActionResult Edit(LeaveRequest leaveRequest)
    {
        _context.LeaveRequest.Update(leaveRequest);
        _context.SaveChanges();

        return RedirectToAction("Index");
    }


    [Authorize]
    public IActionResult Delete(int id)
    {
        var leaveRequest = _context.LeaveRequest.FirstOrDefault(lr => lr.Id == id);
        if (leaveRequest == null)
        {
            return NotFound();
        }

        var user = _userManager.GetUserAsync(User).Result;

        // Check if the user is an admin
        if (User.IsInRole("Admin"))
        {
            // Admins can delete any LeaveRequest
            _context.LeaveRequest.Remove(leaveRequest);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // Check if the leave request belongs to the current user
        if (leaveRequest.EmployeeId != user.Id)
        {
            return Unauthorized();
        }

        // Non-admin users can only delete their own LeaveRequests
        _context.LeaveRequest.Remove(leaveRequest);
        _context.SaveChanges();
        return RedirectToAction("MyLeaveRequests");
    }

    [Authorize(Roles = "Employee")]
    public IActionResult MyLeaveRequests()
    {
        // Get the currently logged-in user
        var user = _userManager.GetUserAsync(User).Result;

        // Fetch LeaveRequests for the logged-in user
        var leaveRequests = _context.LeaveRequest
            .Include(lr => lr.LeaveType)
            .Where(lr => lr.EmployeeId == user.Id)
            .ToList();

        return View(leaveRequests);
    }

    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> AcceptRequest(int id)
    {
        var leaveRequest = _context.LeaveRequest.FirstOrDefault(lr => lr.Id == id);
        if (leaveRequest == null)
        {
            return NotFound();
        }

        if(leaveRequest.Status == "Pending")
        {
 
            int daysToDeduct = (leaveRequest.EndDate - leaveRequest.StartDate).Days;

            var allocatedLeave = _context.LeaveAllocation.FirstOrDefault(la => la.EmployeeId == leaveRequest.EmployeeId && la.LeaveTypeId == leaveRequest.LeaveTypeId);

            if(allocatedLeave != null)
            {
                


                if (allocatedLeave.NumberOfDays >= daysToDeduct)
                {
                    allocatedLeave.NumberOfDays -= daysToDeduct;

                    leaveRequest.Status = "Accepted";


                    _context.LeaveAllocation.Update(allocatedLeave);

                    _context.LeaveRequest.Update(leaveRequest);

                    _context.SaveChanges();
                }
                else
                {
                    TempData["InsufficientLeaveDaysMessage"] = "The employee does not have enough days to take out this request. Consider editing the employees Allocation days or just straight up deny the request ";
                    return RedirectToAction("Index");

                }
            }
        }









        leaveRequest.Status = "Accepted";

        ////------------------------------- 

        var emailaddresses = _context.Users.Select(x => x.Email); //Finds the Email of select user depending on LeaveRequest
        foreach (var emailaddress in emailaddresses) //Loops through all emails and sends message depending on user's email
        {
            var receiver = emailaddress;
            var subject = "Leave Request";
            var message = "You've got a message from the Leave management system";

            await _emailSender.SendEmailAsync(receiver, subject, message);
        }

        _context.LeaveRequest.Update(leaveRequest);
        _context.SaveChanges();

        return RedirectToAction("Index");
    }

    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> DenyRequest(int id)
    {
        var leaveRequest = _context.LeaveRequest.FirstOrDefault(lr => lr.Id == id);
        if (leaveRequest == null)
        {
            return NotFound();
        }


        leaveRequest.Status = "Declined";



        var emailaddresses = _context.Users.Select(x => x.Email);
        foreach (var emailaddress in emailaddresses)
        {
            var receiver = emailaddress;
            var subject = "Leave Request";
            var message = "You've got a message from the Leave management system";

            await _emailSender.SendEmailAsync(receiver, subject, message);

            

        }

        _context.LeaveRequest.Update(leaveRequest);
        _context.SaveChanges();

        return RedirectToAction("Index");
    }
}

LeaveManagementT5/Controllers/LeaveTypesController.cs
using Microsoft.AspNetCore.Mvc;
using LeaveManagementT5.Data;
using LeaveManagementT5.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace LeaveManagementT5.Controllers
{
    [Authorize(Roles ="Admin")]
    public class LeaveTypesController : Controller
    {
        private readonly AppDbContext _context;

        public LeaveTypesController(AppDbContext context)
        {
            _context = context;
            
        }


        public IActionResult Index()
        {
            var leaveTypes = _context.LeaveTypes.ToList();
            return View(leaveTypes);
            
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(LeaveType leaveType)
        {
            if (ModelState.IsValid)
            {
                _context.LeaveTypes.Add(leaveType);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(leaveType);
        }

        public IActionResult Edit(int id)
        {
            var leaveType = _context.LeaveTypes.Find(id);
            if (leaveType == null)
            {
                return NotFound();
            }
            return View(leaveType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, LeaveType leaveType)
        {
            if (id != leaveType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(leaveType);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(leaveType);
        }

        public IActionResult Delete(int id)
        {
            var leaveType = _context.LeaveTypes.Find(id);
            if (leaveType == null)
            {
                return NotFound();
            }
            return View(leaveType);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var leaveType = _context.LeaveTypes.Find(id);
            if (leaveType != null)
            {
                _context.LeaveTypes.Remove(leaveType);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.LeaveTypes == null)
            {
                return NotFound();
            }

            var leaveType = await _context.LeaveTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leaveType == null)
            {
                return NotFound();
            }

            return View(leaveType);
        }
    }
}

LeaveManagementT5/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using LeaveManagementT5.Models;
using LeaveManagementT5.Data;
using Microsoft.AspNetCore.Authorization;

namespace LeaveManagementT5.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
       

        public UserController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
            
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DisplayUsers()
        {
           
           var users = _userManager.Users
           .Select(u => new UserViewModel
           {
                
             Id = u.Id,
             UserName = u.UserName,
             //Email = u.Email, //Email är exakt samma som username, känns inte nödvändgit att ha med det två gånger
             PhoneNumber = u.PhoneNumber,
             FirstName = (string)u.GetType().GetProperty("FirstName").GetValue(u, null),
             LastName = (string)u.GetType().GetProperty("LastName").GetValue(u, null),
                
           }).ToList();

           return View("DisplayUser", users);
            
        }



    }
}

LeaveManagementT5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LeaveManagementT5</title>
    <link rel="icon" type="image/x-icon" href="~/Images/favicon-32x32.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LeaveManagementT5.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<body>
   
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/logo.png" alt="Your Logo" class="logo-image" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                                            
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationRoles" asp-action="Index">Roles</a> 
                            </li>
                        }

                          @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="LeaveTypes" asp-action="Index">LeaveTypes</a>
                            </li>
                        }

                       

                        @if(User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="LeaveAllocation" asp-action="Index">Create LeaveAllocation</a>
                            </li>
                            
                        }

                        <!-- Jobbar med denna -->
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="DisplayUsers">View Users</a>
                            </li>
                        }

                        


                        @if (User.IsInRole("Employee"))
                        {
                            <a class="nav-link text-dark" asp-area="" asp-controller="LeaveAllocation" asp-action="EmployeeLeaveAllocations">My LeaveAllocations</a>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="LeaveRequest" asp-action="Index">View LeaveRequest</a>
                            </li>

                        }

                        @if (User.IsInRole("Employee"))
                        {
                            <a class="nav-link text-dark" asp-area="" asp-controller="LeaveRequest" asp-action="Create">Create LeaveRequest</a>
                        }

                        @if (User.IsInRole("Employee"))
                        {
                            <a class="nav-link text-dark" asp-area="" asp-controller="LeaveRequest" asp-action="MyLeaveRequests">My LeaveRequest</a>
                        }

                       
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @if (User.IsInRole("Employee"))
            {
                <h1></h1>
            }
            @if(User.IsInRole("Admin"))
            {
                <h1></h1>
            }

          
        </main>
    </div>

   
  


    <footer class="border-top footer text-muted" style="background-color: #0057b8; height: 10%;">

        <div class="container" style="color:white;">
            &copy; 2023 - LeaveManagementT5 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>